name: deploy react

on: 
  push:
    branches: 
      - master

jobs:
  build: 
    runs-on: ubuntu-latest

    steps: 
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build Docker image
      - name: Build Docker image
        run: docker build -t nasser00/react-test -f Dockerfile.dev .

      # Run tests
      - name: Run tests
        run: docker run -e CI=true nasser00/react-test npm run test

      # Tag image with Git SHA (so each push is unique)
      - name: Tag Docker image
        run: docker tag nasser00/react-test nasser00/react-test:${{ github.sha }}

      # Push image to Docker Hub
      - name: Push Docker image
        run: |
          docker push nasser00/react-test
          docker push nasser00/react-test:${{ github.sha }}

      # Create deployment package (for Elastic Beanstalk)
      - name: Create deployment package
        run: zip -r deploy.zip . -x '*.git*'

      # Deploy to Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20  
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: "Deployment React-test"
          environment_name: "DeploymentReact-test-env"
          region: "us-east-1"
          version_label: ${{ github.sha }}
          deployment_package: "deploy.zip"
