name: deploy react

on: 
  push:
    branches: 
      - master

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t nasser00/react-test -f Dockerfile.dev .

      - name: Run tests
        run: docker run -e CI=true nasser00/react-test npm run test

      - name: Create deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20  
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: "Deployment React-test"
          environment_name: "DeploymentReact-test-env"
          region: "us-east-1"
          version_label: ${{ github.sha }}
          deployment_package: "deploy.zip"
